Document: roai
Title: Debian roai Manual
Author: <insert document author here>
Abstract: This manual describes what roai is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/roai/roai.sgml.gz

Format: postscript
Files: /usr/share/doc/roai/roai.ps.gz

Format: text
Files: /usr/share/doc/roai/roai.text.gz

Format: HTML
Index: /usr/share/doc/roai/html/index.html
Files: /usr/share/doc/roai/html/*.html
